In [1]:
import numpy as np

In [3]:
np_arr1 = np.array([1,2,3,4])
np_arr1

array([1, 2, 3, 4])

In [4]:
np_arr2 = np.array([[1,2,3,4],[11,12,13,14]])
np_arr2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [5]:
np_arr3 = np.array([[[1,2,3,4],[11,12,13,14]],[[21,22,23,24],[31,32,33,34]]])
np_arr3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [7]:
print(np_arr1.shape)
print(np_arr2.shape)
print(np_arr3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [10]:
z1 = np.zeros([4])
o2 = np.ones([3,4])
r2 = np.random.rand(2,3)

In [11]:
z1,o2,r2

(array([0., 0., 0., 0.]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[0.57470876, 0.52000825, 0.97215324],
        [0.69064795, 0.15836802, 0.67739156]]))

In [12]:
print(z1.shape)
print(o2.shape)
print(r2.shape)

(4,)
(3, 4)
(2, 3)


In [13]:
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[-0.215, -1.037, -1.068,  0.483,  1.004],
         [ 1.03 ,  0.18 ,  0.152,  0.167, -0.842],
         [-0.074, -1.082,  1.299,  1.204, -0.871],
         [ 0.355, -1.864, -0.898,  0.401,  0.296]],

        [[-0.436,  1.691,  0.428,  0.343, -0.352],
         [-1.63 , -2.766,  0.987, -0.463,  1.032],
         [ 2.114, -1.647,  0.775,  0.718, -1.371],
         [-1.49 ,  0.616,  0.227,  1.344,  0.332]]],


       [[[ 0.409,  0.278,  0.104, -0.834, -0.371],
         [ 0.767, -0.324, -0.637, -1.104, -0.228],
         [ 1.958,  1.373, -0.625,  0.535, -0.272],
         [ 1.341,  0.432,  0.411, -0.785,  0.938]],

        [[ 2.153, -0.326,  0.331, -0.672, -0.252],
         [-0.035, -0.047,  2.699, -1.53 ,  0.274],
         [ 1.263,  1.756,  2.521, -2.2  ,  0.936],
         [ 0.726, -1.392,  0.518, -1.404, -0.191]]]])

In [14]:
r4[1][0]

array([[ 0.409,  0.278,  0.104, -0.834, -0.371],
       [ 0.767, -0.324, -0.637, -1.104, -0.228],
       [ 1.958,  1.373, -0.625,  0.535, -0.272],
       [ 1.341,  0.432,  0.411, -0.785,  0.938]])

In [15]:
r4[1][0][2]

array([ 1.958,  1.373, -0.625,  0.535, -0.272])

In [16]:
r4[1][0][2][4]

-0.272

In [17]:
r4[1][0][0:4:2]

array([[ 0.409,  0.278,  0.104, -0.834, -0.371],
       [ 1.958,  1.373, -0.625,  0.535, -0.272]])

In [18]:
r4[1][0][1:4:2]

array([[ 0.767, -0.324, -0.637, -1.104, -0.228],
       [ 1.341,  0.432,  0.411, -0.785,  0.938]])

In [20]:
r4[1][0][1:4:2][1,3:]

array([-0.785,  0.938])

In [22]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [23]:
arr + arr

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [24]:
arr * arr

array([[  1,   4,   9,  16],
       [100, 121, 144, 169]])

In [25]:
arr + 20

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [26]:
arr * arr

array([[  1,   4,   9,  16],
       [100, 121, 144, 169]])

In [27]:
arr * 100

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [28]:
arr.sum(), arr.mean(), arr.prod(), arr.max(), arr.min()

(56, 7.0, 411840, 13, 1)

In [30]:
arr[1].min(), arr[1][2:].sum()

(10, 25)

In [31]:
arr.argmax(), arr[1].argmax(), arr.argmin()

(7, 3, 0)